name: Create PR 

on: 
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  gh-pr-create:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref }} == "release"
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B release \
            -H ${{ github.event.pull_request.head.ref }} \
            -t "Merge release into develop" \
            -b "This PR was created by the automation workflow." \
            -a "${{ github.event.pull_request.user.login }}" \
            -l "enhancement"
            -l "help wanted"
            -r ${{ github.event.repository.owner.login }} 
      
