name: Create PR 

on: 
  push:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  gh-pr-create:
    runs-on: ubuntu-latest
    if: ${{ github.event.push.ref }} == "release"
    
    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ github.event.push }}"
        
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B develop \
            -H ${{ github.event.push.base_ref }} \
            -t "Merge release into develop" \
            -b "This PR was created by the automation workflow." \
            -a "${{ github.event.push.pusher.name }}" \
            -l "enhancement,help wanted"
            -r ${{ github.event.repository.owner.login }} 
      
