name: Create PR 

on: 
  push:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  gh-pr-create:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref }} == "release"
    
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "BaseRef: ${{ github.base_ref }}"
          echo "HeadRef: ${{ github.head_ref }}"
          echo "Ref: ${{ github.ref }}"
        
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B develop \
            -H ${{ github.head_ref }} \
            -t "Merge release into develop" \
            -b "This PR was created by the automation workflow." \
            -a "${{ github.actor }}" \
            -l "enhancement,help wanted"
            -r ${{ github.event.repository.owner.login }} 
      
