name: Print Environment Variables

on: 
  push:
  workflow_dispatch:

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
  set_env:
    runs-on: ubuntu-latest
    needs: checkout_code
    outputs:
      TAG: ${{ steps.set_env.outputs.TAG }}

    steps:
      - name: Set environment variables
        id: set_env
        uses: ./set_env.yaml
        
  
  print_env:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Print Environment Variables
        run: |
          echo "TAG: ${{ needs.set_env.outputs.TAG }}"