name: Print Environment Variables

on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  set_env:
    name: Set Environment Variables
    uses: amartins-alexandre/actionflows/.github/workflows/set_env.yml@main
  
  print_env:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Environment Variables
        run: |
          echo "TAG: ${{ needs.set_env.outputs.TAG }}"