on: 
  push: 
    branches: [main, develop]

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update Modules Python3
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

  approval-request:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - run: echo "${{ github..actor }}"
        
      

    
  
    
