name: Replace ARG Example

on: [workflow_dispatch]

jobs:
  replace-example:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar variável com prefixo
        run: echo "HOST=https://qualquercoisa.com" >> $GITHUB_ENV

      - name: Remover o prefixo "https://"
        run: |
          CLEANED_HOST=${HOST#https://}
          echo "CLEANED_HOST=${CLEANED_HOST}" >> $GITHUB_ENV

      - name: Exibir resultado
        run: echo "Host limpo: $CLEANED_HOST"
