name: Set Environment Variables

on: 
  workflow_call:
    outputs:
      TAG:
        description: 'The tag to be set'
        value: ${{ jobs.set_env.outputs.TAG }}
      BRANCH:
        description: 'The branch to be set'
        value: ${{ jobs.set_env.outputs.BRANCH }}

jobs:
  set_env:
    runs-on: ubuntu-latest

    outputs:
      TAG: ${{ steps.set_env.outputs.TAG }}
      BRANCH: ${{ steps.set_env.outputs.BRANCH }}

    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          echo "TAG=1.0.0" >> $GITHUB_OUTPUT
          echo "BRANCH=main" >> $GITHUB_OUTPUT