name: Set Environment Variables

on: 
  workflow_call:

jobs:
  set_env:
    runs-on: ubuntu-latest
    
    outputs:
      TAG: ${{ steps.tag_create.outputs.TAG }}
    
    steps:
      - name: Tag Create
        id: tag_create
        run: |
          echo "TAG::${{ github.ref }}:${{ github.run_number }}" >> GITHUB_ENV