name: Set Environment Variables

on: 
  workflow_call:
    outputs:
      TAG: ${{ github.ref }}:${{ github.run_number }}

jobs:
  set_env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0