name: Set Environment Variables

on: 
  workflow_call:

jobs:
  set_env:
    runs-on: ubuntu-latest

    outputs:
      TAG: ${{ steps.set_env.outputs.TAG }}
      BRANCH: ${{ steps.set_env.outputs.BRANCH }}

    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          echo "Setting environment variables..."
          echo "TAG=1.0.0" >> $GITHUB_ENV
          echo "BRANCH=main" >> $GITHUB_ENV