name: NPM Version

on: [workflow_dispatch]

jobs:
  new_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Update Version
        run: |
          jq -r '.version' package.json

          git config --global user.name "github-actions[bot]"
          git config --globaç user.email "github-actions[bot]@users.noreply.github.com"
          npm version $(cat version.txt)
          jq -r '.version' package.json
  