name: User Input

on: 
  workflow_dispatch:
    inputs:
      PACKAGE_VERSION:
        description: 'Package Version'
        required: true
        type: string
      # target_branch:
      #   description: "Selecione a branch"
      #   required: true
      #   default: "main"
      #   type: choice
      #   options:
      #     - main
      #     - develop
      #     - release

jobs:
  user-input:
    runs-on: ubuntu-latest
    steps:
      - name: User Input Version
        run: |
          echo "Version=${{ inputs.PACKAGE_VERSION }}"
      
